"""Default-continuous Engine host. A tick never creates Subject content."""
from contextlib import contextmanager
from datetime import timedelta
from uuid import uuid4
import sys

from continuity_engine.domain.action_planning import digest, identifier
from continuity_engine.domain.persistent_runtime import RuntimeBoundaryError, RuntimeDeferred, RuntimePolicy, stamp, parse, utc
from continuity_engine.domain.scheduling import SchedulerTask, SchedulerWakeReason, SchedulerTickStatus, SchedulerAdmissionStatus
from continuity_engine.domain.subject_lifecycle import lifecycle_status
from continuity_engine.storage.json_runtime_repository import file_lock, RuntimeCheckpointBusy
from .runtime_ports import InterruptibleWait


class PersistentRuntimeService:
    def __init__(self, repository, scheduler, work, subject_states, identities, *, clock, policy=None, waiter=None):
        self.repository=repository;self.scheduler=scheduler;self.work=work;self.subject_states=subject_states
        self.identities=identities;self.clock=clock;self.policy=policy or RuntimePolicy();self.waiter=waiter or InterruptibleWait()
        self.subject_id=repository.subject_id;self.environment=repository.environment
        self.owner=None;self.generation=None;self.hook=None
        self._checkpoint_waiting=False
        if (work.subject_id,work.environment)!=(self.subject_id,self.environment):raise RuntimeBoundaryError('RUNTIME_WORK_BINDING')
        work.guard=self.guard

    def _principal(self,handle,operation):
        try:p=self.identities.resolve(handle)
        except Exception:raise RuntimeBoundaryError('RUNTIME_CONTROL_IDENTITY_UNAVAILABLE') from None
        if p is None or (p.subject_id,p.environment)!=(self.subject_id,self.environment) or operation not in p.operations:
            raise RuntimeBoundaryError('RUNTIME_CONTROL_DENIED')
        return p

    def control(self,operation,*,command_id,expected_revision,handle):
        if operation not in {'PAUSE','RESUME','STOP'}:raise RuntimeBoundaryError('RUNTIME_CONTROL_OPERATION')
        identifier(command_id)
        principal=self._principal(handle,operation)
        identity=digest(command_id)
        key=digest([command_id,operation,expected_revision,principal.principal_id,self.subject_id,self.environment])
        with self.repository.transaction() as d:
            if d is None:raise RuntimeBoundaryError('RUNTIME_NOT_INITIALIZED')
            current=self._principal(handle,operation)
            if current!=principal:raise RuntimeBoundaryError('RUNTIME_CONTROL_CHANGED')
            old=next((c for c in d['commands'] if c['id']==identity),None)
            if old is not None:
                if old['hash']!=key:raise RuntimeBoundaryError('RUNTIME_CONTROL_IDENTITY_CONFLICT')
                return d
            if expected_revision is not None and (type(expected_revision) is not int or expected_revision!=d['revision']):
                raise RuntimeBoundaryError('RUNTIME_CONTROL_REVISION_CONFLICT')
            if d['desired']=='STOPPED':
                # STOP is terminal even for a new caller command identity.
                # Reasserting STOP is already satisfied and creates no history;
                # PAUSE/RESUME cannot overlay the persisted terminal decision.
                if operation=='STOP':return d
                raise RuntimeBoundaryError('RUNTIME_STOP_IS_TERMINAL')
            if operation=='RESUME':
                self.subject_states.require_active(self.subject_id,self.environment)
            d['desired']={'PAUSE':'PAUSED','RESUME':'RUNNING','STOP':'STOPPED'}[operation]
            d['state']={'PAUSE':'PAUSED','RESUME':'RESUME','STOP':'STOP'}[operation]
            d['activity']={'PAUSE':'PAUSED','RESUME':'IDLE','STOP':'STOPPED'}[operation]
            d['reason']='OWNER_'+operation;d['next_check_at']=None
            # Owner commands are explicit, not generated by idle ticks. Retain
            # their digests so eviction cannot turn an old PAUSE into new work.
            # Raw opaque caller material never enters the checkpoint or query.
            d['commands'].append(dict(id=identity,hash=key,operation=operation,revision=d['revision']+1))
            self.repository.save(d)
        self.waiter.interrupt()
        return d

    def query(self):
        d=self.repository.load()
        tasks=self.scheduler.list_tasks(subject_id=self.subject_id,environment=self.environment)
        from continuity_engine.domain.scheduling import TERMINAL_STATES
        resources=self.work.resources.get_resource_state(self.subject_id)
        return {**d,'host_alive':self.repository.host_alive(),'checkpoint_busy':self.repository.checkpoint_busy(),
                'subject_lifecycle':lifecycle_status(self.subject_states.load(self.subject_id)),
                'pending_tasks':sum(t.state not in TERMINAL_STATES for t in tasks),
                'unconfirmed_tasks':sum(t.state.value=='UNKNOWN' for t in tasks),
                'resources':dict(token_budget=resources.token_budget,token_used=resources.token_used,
                    token_remaining=resources.token_remaining,compute_remaining=resources.compute_remaining)}

    @staticmethod
    def _interruption(d,reason):
        d['interruptions']=(d['interruptions']+[dict(generation=d['generation'],reason=reason,last_trusted_time=d['last_time'])])[-64:]

    @contextmanager
    def running(self):
        if self.owner is not None:raise RuntimeBoundaryError('RUNTIME_ALREADY_ATTACHED')
        with file_lock(self.repository.owner_path):
            with self.repository.transaction() as d:
                if d is None:raise RuntimeBoundaryError('RUNTIME_NOT_INITIALIZED')
                if d['desired']!='STOPPED':
                    previous=d['owner']
                    if previous:self._interruption(d,'PRIOR_HOST_LOST')
                    d['owner']='owner:'+uuid4().hex;d['generation']+=1
                    d['state']='RECOVER' if previous else ('PAUSED' if d['desired']=='PAUSED' else 'START')
                    d['reason']='PROCESS_INTERRUPTED_RECOVER' if previous else 'HOST_ATTACHED'
                    self.repository.save(d)
                self.owner=d['owner'];self.generation=d['generation']
            interrupted=False
            try:yield self
            except BaseException:
                interrupted=True
                raise
            finally:
                try:
                    with self.repository.transaction() as d:
                        if d is not None and (d['owner'],d['generation'])==(self.owner,self.generation):
                            # Closing an attachment is not an Owner STOP.
                            if d['desired']=='STOPPED':d['owner']=None
                            else:
                                if interrupted:self._interruption(d,'PROCESS_INTERRUPTED')
                                d['state']='SUSPENDED';d['reason']='HOST_DETACHED'
                                self._interruption(d,'HOST_DETACHED')
                            self.repository.save(d)
                except RuntimeCheckpointBusy:
                    # The OS owner lock still releases. Leave the old owner
                    # for the next attachment to verify as PRIOR_HOST_LOST.
                    # Never retry an exit diagnostic by writing the busy lock.
                    print('RUNTIME_EXIT_CHECKPOINT_BUSY',file=sys.stderr,flush=True)
                except Exception:
                    if not interrupted:raise
                    # Preserve the original failure, even if recording it fails.
                    print('RUNTIME_EXIT_CHECKPOINT_UNAVAILABLE',file=sys.stderr,flush=True)
                finally:self.owner=None;self.generation=None

    def guard(self,stage='before_dispatch'):
        if self.hook:self.hook(stage)
        d=self.repository.load()
        if self.owner is None or (d['owner'],d['generation'])!=(self.owner,self.generation):
            raise RuntimeDeferred('RUNTIME_STALE_OWNER')
        if d['desired']!='RUNNING':raise RuntimeDeferred('RUNTIME_CONTROL_PAUSED_OR_STOPPED')
        now=utc(self.clock())
        if d['last_time'] is not None and now<parse(d['last_time']):raise RuntimeDeferred('RUNTIME_CLOCK_REGRESSION')
        self.subject_states.require_active(self.subject_id,self.environment)

    def _observe(self,*,state='RUNNING',activity='IDLE',reason='IDLE',now=None,last_task=None,delay=None,control_revision=None):
        with self.repository.transaction() as d:
            if d is None or (d['owner'],d['generation'])!=(self.owner,self.generation):raise RuntimeBoundaryError('RUNTIME_STALE_OWNER')
            if d['desired']=='STOPPED':return False
            current_control=d['commands'][-1]['revision'] if d['commands'] else 0
            if control_revision is not None and current_control!=control_revision:
                # A control committed while this observation waited. Keep its
                # state/watermark intact and re-evaluate on the next tick.
                return True
            if d['desired']=='PAUSED':state,activity,reason='PAUSED','PAUSED','OWNER_PAUSE'
            updates=dict(state=state,activity=activity,reason=reason)
            if now is not None:
                if d['last_time'] is None or now>=parse(d['last_time']):updates['last_time']=stamp(now)
                updates['next_check_at']=stamp(now+timedelta(seconds=delay if delay is not None else self.policy.idle_wait_seconds))
            if last_task is not None:updates['last_task']=last_task
            if any(d[k]!=v for k,v in updates.items()):
                d.update(updates);d['observations']+=1;self.repository.save(d)
        return True

    def tick(self):
        try:result=self._tick()
        except RuntimeCheckpointBusy:
            self._checkpoint_backoff()
            return True
        if self._checkpoint_waiting:
            print('RUNTIME_CHECKPOINT_AVAILABLE',file=sys.stderr,flush=True)
            self._checkpoint_waiting=False
        return result

    def _checkpoint_backoff(self):
        # Diagnostic is process-local because the checkpoint cannot be written.
        # One message per busy interval, no arbitrary exception text or retries
        # of effects. serve() still performs its interruptible wait after tick.
        if not self._checkpoint_waiting:
            print('RUNTIME_CHECKPOINT_BUSY',file=sys.stderr,flush=True)
        self._checkpoint_waiting=True

    def _tick(self):
        d=self.repository.load()
        control_revision=d['commands'][-1]['revision'] if d['commands'] else 0
        def observe(**fields):return self._observe(control_revision=control_revision,**fields)
        if d['desired']=='STOPPED':return False
        if self.owner is None or d['owner']!=self.owner or d['generation']!=self.generation:
            raise RuntimeBoundaryError('RUNTIME_STALE_OWNER')
        if d['desired']=='PAUSED':return observe(state='PAUSED',activity='PAUSED',reason='OWNER_PAUSE')
        lifecycle=lifecycle_status(self.subject_states.load(self.subject_id))
        if lifecycle!='ACTIVE':
            return observe(state='ARCHIVED' if lifecycle in {'ARCHIVED','DELETED'} else 'SUSPENDED',activity='PAUSED',reason='SUBJECT_'+lifecycle)
        try:now=utc(self.clock())
        except Exception:return observe(state='SUSPENDED',activity='CLOCK_WAIT',reason='CLOCK_INVALID')
        if d['last_time'] is not None and now<parse(d['last_time']):
            return observe(state='SUSPENDED',activity='CLOCK_WAIT',reason='CLOCK_REGRESSION')
        if d['next_check_at'] is not None and now<parse(d['next_check_at']):return True
        jumped=d['last_time'] is not None and (now-parse(d['last_time'])).total_seconds()>self.policy.clock_jump_seconds
        try:
            self.guard('before_needs')
            needs=self.work.needs(now)
            if len(needs)>2:raise RuntimeBoundaryError('RUNTIME_NEEDS_BOUND_EXCEEDED')
            pressure=False
            for need in needs:
                admission=self.scheduler.submit(SchedulerTask.create(task_id=need.identity,subject_id=self.subject_id,environment=self.environment,
                    priority=need.priority,due_at=need.due_at,wake_reason=SchedulerWakeReason.INTERNAL,
                    cycle_id=self.work.cycle_id,created_at=need.due_at,max_attempts=self.policy.max_failures))
                pressure=pressure or admission.status is SchedulerAdmissionStatus.BACKPRESSURE
            self.guard('before_scheduler')
            result=self.scheduler.tick(self.subject_id,self.environment)
            task=result.task
            if result.status in {SchedulerTickStatus.COMPLETED,SchedulerTickStatus.RECONCILED_COMPLETED}:
                self.work.fault('after_scheduler_completed')
                return observe(activity='MAINTENANCE' if task.task_id.startswith('maintenance:') else 'COGNITION',reason='TASK_COMPLETED',
                    now=now,last_task=task.task_id,delay=self.policy.minimum_spacing_seconds)
            if result.status is SchedulerTickStatus.RESOURCE_DEFERRED:
                return observe(activity='WAITING_RESOURCES',reason='TASK_RESOURCES_UNAVAILABLE',now=now,delay=self.policy.retry_seconds)
            if result.status is SchedulerTickStatus.VERIFICATION_PENDING:
                return observe(activity='WAITING_VERIFICATION',reason='TASK_RESULT_UNCONFIRMED',now=now,delay=self.policy.retry_seconds)
            if result.status in {SchedulerTickStatus.RETRY_EXHAUSTED,SchedulerTickStatus.RETRY_SCHEDULED}:
                return observe(activity='BACKOFF',reason='TASK_RETRY_BOUND',now=now,delay=self.policy.retry_seconds)
            if pressure:
                return observe(activity='BACKOFF',reason='QUEUE_BACKPRESSURE',now=now,delay=self.policy.retry_seconds)
            return observe(reason='CLOCK_GAP_COALESCED' if jumped else 'NO_CURRENT_NEED',now=now)
        except RuntimeCheckpointBusy:
            raise
        except RuntimeDeferred:
            return observe(activity='BACKOFF',reason='CURRENT_ADMISSION_DEFERRED',now=now,delay=self.policy.retry_seconds)
        except Exception:
            # Arbitrary adapter exception text/tracebacks are never persisted.
            return observe(activity='BACKOFF',reason='WORK_PORT_UNAVAILABLE',now=now,delay=self.policy.retry_seconds)

    def serve(self):
        """Default product lifetime: no max ticks, deadline, random exit or UI dependency."""
        while True:
            try:
                with self.running():
                    while self.tick():
                        self.waiter.wait(self.policy.idle_wait_seconds)
                return
            except RuntimeCheckpointBusy:
                # A competing control may also precede the first attachment.
                # This is not the owner lock's immediate RUNTIME_BUSY rejection.
                self._checkpoint_backoff()
                self.waiter.wait(self.policy.idle_wait_seconds)
