"""Continuity Engine public package surface."""

from .domain.awakening import (
    AwakeCycle,
    AwakeMode,
    AwakeningResult,
    WakeAction,
    WakeContext,
    WakeDecision,
    WakeReason,
    WakeSession,
    WakeTimeInfo,
    WakeTrigger,
)
from .domain.awakening_rules import WakeDecisionPolicy
from .domain.models import (
    ContinuityState,
    EmotionState,
    IdentityState,
    IntentionsState,
    RelationshipState,
    SubjectState,
    TemporalState,
)
from .domain.events import (
    ChangeOperation,
    Event,
    EventClassification,
    EventEvidenceReference,
    EventReference,
    EventRelationType,
    EventSourceKind,
    EventTimeBasis,
    StateMutation,
    StateSection,
    StateUpdateRecord,
)
from .domain.timeline import (
    TimelineEntry,
    TimelineEventStatus,
    TimelineProjection,
    TimelineQuery,
    TimelineRelativeOrder,
    TimelineResult,
)
from .domain.context_routing import (
    CandidateDecision,
    CandidateDecisionStatus,
    CandidateManifest,
    ContextCandidateReference,
    ContextPartition,
    ContextPartitionRequest,
    ContextRouteResult,
    ContextRouteStatus,
    ContextRoutingRequest,
    ContextSourceBatch,
    ContextSourceCandidate,
    ContextTrace,
    PartitionDecisionStatus,
    PartitionTrace,
    RetrievalBudget,
    RoutePlan,
    RoutingSignal,
    SourceTrace,
)
from .domain.context_composition import (
    ComposedContextFragment,
    ComposedContextSnapshot,
    CompositionDecision,
    CompositionDecisionStatus,
    CompositionStatus,
    CompositionTrace,
    ContextAuthority,
    ContextBudget,
    ContextCompositionResult,
    MissingContextNotice,
    ResolverReadCount,
    ResolvedContextMaterial,
    composition_hash,
)
from .domain.errors import (
    ContextCompositionError,
    ContextCompositionSourceError,
    ContextCompositionValidationError,
    ContextRoutingError,
    ContextRoutingSourceError,
    ContextRoutingValidationError,
)
from .domain.evolution import StateEvolutionResult, SubjectStateEvolver
from .domain.integration_contract import (
    Constraints,
    ContinuityInteractionRequest,
    Conversation,
    Identity,
    MessageVersionFact,
    PlatformFactPackage,
    PlatformObservation,
    SubjectBindingFixture,
)
from .domain.integration_results import (
    FirstRoundError,
    FirstRoundErrorCode,
    FirstRoundErrorEnvelope,
    FirstRoundRetryClass,
    FirstRoundSubjectResponse,
    FirstRoundSuccessResult,
    LedgerLookupResult,
    LedgerLookupStatus,
    SubjectStateProjection,
    SubjectStateProjectionSnapshot,
)
from .domain.memory import (
    MemoryCandidate,
    MemoryInfluenceRecord,
    MemoryRelevanceDecision,
    MemoryRelevancePolicy,
    MemoryRetrievalRequest,
    MemoryRetrievalResult,
)
from .domain.learning import (
    LEARNABLE_FIELD_PATHS,
    LearningCandidateResult,
    LearningChangeResult,
    LearningContext,
    LearningEvent,
    LearningRecord,
    LearningRecordType,
    LearningResult,
    LearningValidationStatus,
    PersonalityTrait,
)
from .domain.thinking import (
    ThinkSession,
    ThinkingDepth,
    ThinkingExecutionResult,
    ThinkingResult,
    TokenBudget,
    TokenBudgetRequest,
    WakePerceptionThinkingResult,
)
from .domain.perception import (
    CurrentFocus,
    Drive,
    DriveKind,
    DriveStrength,
    InteractionFrequencyTrend,
    MemoryImpact,
    MemoryInfluence,
    Observation,
    PerceptionContext,
    PerceptionResult,
    RelationshipDirection,
    RelationshipPerception,
    StateStability,
    TemporalMeaning,
    TemporalPerception,
)
from .domain.perception_rules import PerceptionPolicy
from .domain.permissions import (
    PermissionChangeRecord,
    PermissionChangeResult,
    PermissionChangeType,
    PermissionContext,
    PermissionState,
    PermissionStatus,
)
from .domain.resource_policy import DepthCost, ResourcePolicy
from .domain.resources import (
    ResourceAllocation,
    ResourceDecision,
    ResourceRequest,
    ResourceSessionType,
    ResourceState,
    RuntimeMode,
    TokenUsageRecord,
)
from .domain.action import (
    ActionContext,
    ActionDecision,
    ActionExecutionResult,
    ActionIntent,
    ActionPlan,
    ActionPlanStatus,
    ActionSession,
    ActionStep,
    ActionType,
    FailurePolicy,
    PermissionCheck,
    PermissionGrant,
    PerceptionActionSummary,
    ResourceAssessment,
    ResourceLimits,
    RiskAssessment,
    RiskLevel,
    WakePerceptionThinkingActionResult,
)
from .services.action_evaluators import ResourceEvaluator, RiskEvaluator
from .services.action_permissions import (
    DeterministicPermissionProvider,
    InMemoryPermissionProvider,
)
from .services.action_ports import PermissionProvider
from .services.action_service import ActionService
from .services.thinking_ports import ThinkingProvider, TokenBudgetManager
from .services.thinking_service import ThinkingService
from .services.perception_service import PerceptionService
from .services.permission_service import PermissionService
from .services.resource_manager import ResourceManager
from .services.resource_aware_wake_scheduler import (
    ResourceAwareWakeScheduler,
    WakeScheduleResult,
    WakeScheduler,
)
from .services.wake_perception_thinking_service import WakePerceptionThinkingService
from .services.wake_perception_thinking_action_service import (
    WakePerceptionThinkingActionService,
)
from .services.memory_ports import MemoryInfluenceRecorder, MemoryRetriever
from .services.memory_service import MemoryService
from .services.learning_service import LearningService
from .services.integration_contract_hashing import (
    calculate_binding_fixture_hash,
    calculate_content_hash,
    calculate_projection_content_hash,
    calculate_request_hash,
    calculate_state_hash,
    canonicalize_json,
)
from .services.integration_result_factory import FirstRoundResultFactory
from .services.integration_contract_validation import MachineContractValidator
from .services.awakening_service import AwakeningService
from .services.subject_state_service import SubjectStateService
from .services.timeline_service import TimelineService
from .services.context_router_service import (
    ContextCandidateSource,
    ContextPermissionDecision,
    ContextPermissionPolicy,
    ContextRouterService,
    ContextSourceBinding,
    ContextSourceQuery,
    ContextSourceValidation,
    DerivedSummaryContextSource,
    EnginePrivateContextPermissionPolicy,
    MemoryContextSource,
    SubjectStateContextSource,
    TimelineContextSource,
)
from .services.context_material_resolvers import (
    DerivedSummaryMaterialResolver,
    ExactContextMaterialResolver,
    ExactContextPayload,
    MemoryMaterialResolver,
    SubjectStateMaterialResolver,
    TimelineMaterialResolver,
)
from .services.context_composer_service import (
    ContextComposerService,
    ContextTokenEstimator,
    DeterministicContextTokenEstimator,
    TrustedContextResolverBinding,
)
from .services.user_interaction_service import (
    DeterministicReplyComposer,
    InteractionReplyComposer,
    UserInteractionResult,
    UserInteractionService,
)
from .storage.json_repository import JsonSubjectStateRepository
from .storage.json_awakening_repository import JsonAwakeningRepository
from .storage.json_thinking_repository import JsonThinkingRepository
from .storage.json_permission_repository import JsonPermissionRepository
from .storage.json_learning_repository import JsonLearningRepository
from .storage.json_resource_repository import JsonResourceRepository
from .storage.in_memory_action_repository import InMemoryActionRepository
from .storage.json_integration_repository import (
    JsonIntegrationResultLedger,
    JsonSubjectBindingFixtureRepository,
)
from .interfaces import (
    APIBackedSkillAdapter,
    APIError,
    APIRequest,
    APIResponse,
    APIService,
    ActionPlanAPIRequest,
    ActionSessionProvider,
    ChatAPIRequest,
    ContinuityAPI,
    ContinuityMCPAdapter,
    DEFAULT_SCHEMA_REGISTRY,
    EndpointPolicy,
    ExternalOperation,
    FACT_SCHEMA_ID,
    InterfaceAccessError,
    InterfaceAccessGrant,
    InterfaceAccessGuard,
    InterfaceCapability,
    InterfaceOperationError,
    FrontendHTTPServer,
    LocalFrontendApplication,
    LocalSchemaRegistry,
    MemoryAPIRequest,
    PerceptionAPIRequest,
    PerceptionResultProvider,
    RepositoryActionSessionProvider,
    OBSERVATION_SCHEMA_ID,
    REQUEST_SCHEMA_ID,
    SCHEMA_IDS,
    SkillAdapter,
    SubjectStateAPIRequest,
    ThinkingAPIRequest,
    WakeAPIRequest,
    create_frontend_server,
    create_local_frontend_application,
)

__all__ = [
    "Constraints",
    "ContinuityInteractionRequest",
    "Conversation",
    "DEFAULT_SCHEMA_REGISTRY",
    "FACT_SCHEMA_ID",
    "Identity",
    "LocalSchemaRegistry",
    "MachineContractValidator",
    "MessageVersionFact",
    "OBSERVATION_SCHEMA_ID",
    "PlatformFactPackage",
    "PlatformObservation",
    "REQUEST_SCHEMA_ID",
    "SCHEMA_IDS",
    "SubjectBindingFixture",
    "FirstRoundError",
    "FirstRoundErrorCode",
    "FirstRoundErrorEnvelope",
    "FirstRoundRetryClass",
    "FirstRoundSubjectResponse",
    "FirstRoundSuccessResult",
    "LedgerLookupResult",
    "LedgerLookupStatus",
    "SubjectStateProjection",
    "SubjectStateProjectionSnapshot",
    "calculate_binding_fixture_hash",
    "calculate_content_hash",
    "calculate_projection_content_hash",
    "calculate_request_hash",
    "calculate_state_hash",
    "canonicalize_json",
    "FirstRoundResultFactory",
    "APIBackedSkillAdapter",
    "APIError",
    "APIRequest",
    "APIResponse",
    "APIService",
    "ActionContext",
    "ActionDecision",
    "ActionExecutionResult",
    "ActionIntent",
    "ActionPlan",
    "ActionPlanStatus",
    "ActionService",
    "ActionSession",
    "ActionStep",
    "ActionType",
    "ActionPlanAPIRequest",
    "ActionSessionProvider",
    "ChatAPIRequest",
    "ContinuityAPI",
    "ContinuityMCPAdapter",
    "DeterministicPermissionProvider",
    "DeterministicReplyComposer",
    "DepthCost",
    "EndpointPolicy",
    "ExternalOperation",
    "FailurePolicy",
    "InMemoryActionRepository",
    "JsonIntegrationResultLedger",
    "JsonSubjectBindingFixtureRepository",
    "InMemoryPermissionProvider",
    "InterfaceAccessError",
    "InterfaceAccessGrant",
    "InterfaceAccessGuard",
    "InterfaceCapability",
    "InterfaceOperationError",
    "FrontendHTTPServer",
    "LocalFrontendApplication",
    "InteractionReplyComposer",
    "PermissionCheck",
    "PermissionChangeRecord",
    "PermissionChangeResult",
    "PermissionChangeType",
    "PermissionContext",
    "PermissionGrant",
    "PermissionProvider",
    "PermissionService",
    "PermissionState",
    "PermissionStatus",
    "PerceptionActionSummary",
    "ResourceAssessment",
    "ResourceAllocation",
    "ResourceDecision",
    "ResourceEvaluator",
    "ResourceLimits",
    "ResourceManager",
    "ResourcePolicy",
    "ResourceRequest",
    "ResourceSessionType",
    "ResourceState",
    "ResourceAwareWakeScheduler",
    "RiskAssessment",
    "RiskEvaluator",
    "RiskLevel",
    "RuntimeMode",
    "WakePerceptionThinkingActionResult",
    "WakePerceptionThinkingActionService",
    "AwakeCycle",
    "AwakeMode",
    "AwakeningResult",
    "AwakeningService",
    "ContinuityState",
    "CurrentFocus",
    "ChangeOperation",
    "EmotionState",
    "Event",
    "EventClassification",
    "EventEvidenceReference",
    "EventReference",
    "EventRelationType",
    "EventSourceKind",
    "EventTimeBasis",
    "Drive",
    "DriveKind",
    "DriveStrength",
    "IdentityState",
    "IntentionsState",
    "JsonSubjectStateRepository",
    "JsonAwakeningRepository",
    "JsonThinkingRepository",
    "JsonPermissionRepository",
    "JsonLearningRepository",
    "JsonResourceRepository",
    "LEARNABLE_FIELD_PATHS",
    "LearningCandidateResult",
    "LearningChangeResult",
    "LearningContext",
    "LearningEvent",
    "LearningRecord",
    "LearningRecordType",
    "LearningResult",
    "LearningService",
    "LearningValidationStatus",
    "MemoryCandidate",
    "MemoryInfluenceRecord",
    "MemoryInfluenceRecorder",
    "MemoryRelevanceDecision",
    "MemoryRelevancePolicy",
    "MemoryRetrievalRequest",
    "MemoryRetrievalResult",
    "MemoryRetriever",
    "MemoryService",
    "MemoryAPIRequest",
    "MemoryImpact",
    "MemoryInfluence",
    "InteractionFrequencyTrend",
    "Observation",
    "PerceptionContext",
    "PerceptionPolicy",
    "PerceptionResult",
    "PerceptionAPIRequest",
    "PerceptionResultProvider",
    "RepositoryActionSessionProvider",
    "PerceptionService",
    "PersonalityTrait",
    "RelationshipState",
    "RelationshipDirection",
    "RelationshipPerception",
    "StateEvolutionResult",
    "StateMutation",
    "StateSection",
    "StateUpdateRecord",
    "StateStability",
    "SkillAdapter",
    "SubjectStateAPIRequest",
    "SubjectState",
    "SubjectStateEvolver",
    "SubjectStateService",
    "UserInteractionResult",
    "UserInteractionService",
    "TemporalState",
    "TimelineEntry",
    "TimelineEventStatus",
    "TimelineProjection",
    "TimelineQuery",
    "TimelineRelativeOrder",
    "TimelineResult",
    "TimelineService",
    "ThinkSession",
    "ThinkingDepth",
    "ThinkingExecutionResult",
    "ThinkingProvider",
    "ThinkingResult",
    "ThinkingService",
    "ThinkingAPIRequest",
    "TokenBudget",
    "TokenBudgetManager",
    "TokenBudgetRequest",
    "TokenUsageRecord",
    "TemporalMeaning",
    "TemporalPerception",
    "WakeAction",
    "WakeContext",
    "WakeDecision",
    "WakeDecisionPolicy",
    "WakeReason",
    "WakeSession",
    "WakeTimeInfo",
    "WakeTrigger",
    "WakePerceptionThinkingResult",
    "WakePerceptionThinkingService",
    "WakeScheduleResult",
    "WakeScheduler",
    "WakeAPIRequest",
    "create_frontend_server",
    "create_local_frontend_application",
    "CandidateDecision",
    "CandidateDecisionStatus",
    "CandidateManifest",
    "ContextCandidateReference",
    "ContextCandidateSource",
    "ContextPartition",
    "ContextPartitionRequest",
    "ContextPermissionDecision",
    "ContextPermissionPolicy",
    "ContextRouteResult",
    "ContextRouteStatus",
    "ContextRouterService",
    "ContextRoutingRequest",
    "ContextSourceBatch",
    "ContextSourceBinding",
    "ContextSourceCandidate",
    "ContextSourceQuery",
    "ContextSourceValidation",
    "ContextTrace",
    "DerivedSummaryContextSource",
    "EnginePrivateContextPermissionPolicy",
    "MemoryContextSource",
    "PartitionDecisionStatus",
    "PartitionTrace",
    "RetrievalBudget",
    "RoutePlan",
    "RoutingSignal",
    "SourceTrace",
    "SubjectStateContextSource",
    "TimelineContextSource",
    "ContextRoutingError",
    "ContextRoutingSourceError",
    "ContextRoutingValidationError",
    "ComposedContextFragment",
    "ComposedContextSnapshot",
    "CompositionDecision",
    "CompositionDecisionStatus",
    "CompositionStatus",
    "CompositionTrace",
    "ContextAuthority",
    "ContextBudget",
    "ContextCompositionError",
    "ContextCompositionResult",
    "ContextCompositionSourceError",
    "ContextCompositionValidationError",
    "MissingContextNotice",
    "ResolverReadCount",
    "ResolvedContextMaterial",
    "composition_hash",
    "ContextComposerService",
    "ContextTokenEstimator",
    "DeterministicContextTokenEstimator",
    "TrustedContextResolverBinding",
    "DerivedSummaryMaterialResolver",
    "ExactContextMaterialResolver",
    "ExactContextPayload",
    "MemoryMaterialResolver",
    "SubjectStateMaterialResolver",
    "TimelineMaterialResolver",
]
